[Variables]
Test=test
MonthReplaces="January":"Stycze[\x143]","February":"Luty","March":"Marzec","April":"Kwiecie[\x143]","May":"Maj","June":"Czerwiec","July":"Lipiec","August":"Sierpie[\x143]","September":"Wrzesie[\x143]","October":"Pa[\x179]dziernik","November":"Listopad","December":"Grudzie[\x143]"
DayReplaces="Monday":"Poniedzialek","Tuesday":"Wtorek","Wednesday":"Sroda","Thursday":"Czwartek","Friday":"Piatek","Saturday":"Sobota","Sunday":"Niedziela"
RecycleBin=Kosz
RecycleBinFiles=Pliki
RecycleBinSize=Rozmiar
