[Variables]
Test=test
MonthReplaces="January":"Stycze[\324]","February":"Luty","March":"Marzec","April":"Kwiecie[\324]","May":"Maj","June":"Czerwiec","July":"Lipiec","August":"Sierpie[\324]","September":"Wrzesie[\324]","October":"Pa[\378]dziernik","November":"Listopad","December":"Grudzie[\324]"
DayReplaces="Monday":"Poniedzialek","Tuesday":"Wtorek","Wednesday":"Sroda","Thursday":"Czwartek","Friday":"Piatek","Saturday":"Sobota","Sunday":"Niedziela"
RecycleBin=Kosz
RecycleBinFiles=Pliki
RecycleBinSize=Rozmiar
