[MeterBase0]
Meter=String
X=(#Scale#*#LeftOffset#)
Y=(#Scale#*#TopOffset#)
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase1]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase2]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase3]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase4]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase5]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase6]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase7]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase8]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase9]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase10]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase11]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase12]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase13]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase14]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase15]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase16]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase17]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase18]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase19]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase20]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase21]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase22]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase23]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase24]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase25]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase26]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase27]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase28]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase29]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase30]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase31]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase32]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase33]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase34]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase35]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase36]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase37]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase38]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase39]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase40]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase41]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase42]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase43]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase44]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase45]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase46]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase47]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase48]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase49]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase50]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase51]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase52]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase53]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase54]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase55]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase56]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase57]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase58]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase59]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase60]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase61]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase62]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase63]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase64]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase65]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase66]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase67]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase68]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase69]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase70]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase71]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase72]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase73]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase74]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase75]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase76]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase77]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase78]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase79]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))

[MeterBase80]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
FontColor=#VisualizerBandColor#
Text=#Sq2#
AntiAlias=1
Angle=(Rad(270))


;============METERS BANDS===============


[MeterBand0]
Meter=String
X=(#Scale#*#LeftOffset#)
y=(#Scale#*#TopOffset2#)
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand0:%]/100) | 0,0,0,1 ; ([MeasureBand0:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand1]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand1:%]/100) | 0,0,0,1 ; ([MeasureBand1:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand2]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand2:%]/100) | 0,0,0,1 ; ([MeasureBand2:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand3]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand3:%]/100) | 0,0,0,1 ; ([MeasureBand3:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand4]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand4:%]/100) | 0,0,0,1 ; ([MeasureBand4:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand5]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand5:%]/100) | 0,0,0,1 ; ([MeasureBand5:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand6]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand6:%]/100) | 0,0,0,1 ; ([MeasureBand6:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand7]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand7:%]/100) | 0,0,0,1 ; ([MeasureBand7:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand8]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand8:%]/100) | 0,0,0,1 ; ([MeasureBand8:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand9]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand9:%]/100) | 0,0,0,1 ; ([MeasureBand9:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand10]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand10:%]/100) | 0,0,0,1 ; ([MeasureBand10:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand11]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand11:%]/100) | 0,0,0,1 ; ([MeasureBand11:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand12]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand12:%]/100) | 0,0,0,1 ; ([MeasureBand12:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand13]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand13:%]/100) | 0,0,0,1 ; ([MeasureBand13:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand14]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand14:%]/100) | 0,0,0,1 ; ([MeasureBand14:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand15]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand15:%]/100) | 0,0,0,1 ; ([MeasureBand15:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand16]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand16:%]/100) | 0,0,0,1 ; ([MeasureBand16:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand17]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand17:%]/100) | 0,0,0,1 ; ([MeasureBand17:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand18]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand18:%]/100) | 0,0,0,1 ; ([MeasureBand18:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand19]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand19:%]/100) | 0,0,0,1 ; ([MeasureBand19:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand20]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand20:%]/100) | 0,0,0,1 ; ([MeasureBand20:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand21]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand21:%]/100) | 0,0,0,1 ; ([MeasureBand21:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand22]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand22:%]/100) | 0,0,0,1 ; ([MeasureBand22:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand23]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand23:%]/100) | 0,0,0,1 ; ([MeasureBand23:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand24]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand24:%]/100) | 0,0,0,1 ; ([MeasureBand24:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand25]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand25:%]/100) | 0,0,0,1 ; ([MeasureBand25:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand26]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand26:%]/100) | 0,0,0,1 ; ([MeasureBand26:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand27]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand27:%]/100) | 0,0,0,1 ; ([MeasureBand27:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand28]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand28:%]/100) | 0,0,0,1 ; ([MeasureBand28:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand29]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand29:%]/100) | 0,0,0,1 ; ([MeasureBand29:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand30]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand30:%]/100) | 0,0,0,1 ; ([MeasureBand30:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand31]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand31:%]/100) | 0,0,0,1 ; ([MeasureBand31:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand32]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand32:%]/100) | 0,0,0,1 ; ([MeasureBand32:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand33]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand33:%]/100) | 0,0,0,1 ; ([MeasureBand33:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand34]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand34:%]/100) | 0,0,0,1 ; ([MeasureBand34:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand35]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand35:%]/100) | 0,0,0,1 ; ([MeasureBand35:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand36]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand36:%]/100) | 0,0,0,1 ; ([MeasureBand36:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand37]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand37:%]/100) | 0,0,0,1 ; ([MeasureBand37:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand38]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand38:%]/100) | 0,0,0,1 ; ([MeasureBand38:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand39]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand39:%]/100) | 0,0,0,1 ; ([MeasureBand39:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand40]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand40:%]/100) | 0,0,0,1 ; ([MeasureBand40:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand41]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand41:%]/100) | 0,0,0,1 ; ([MeasureBand41:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand42]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand42:%]/100) | 0,0,0,1 ; ([MeasureBand42:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand43]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand43:%]/100) | 0,0,0,1 ; ([MeasureBand43:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand44]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand44:%]/100) | 0,0,0,1 ; ([MeasureBand44:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand45]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand45:%]/100) | 0,0,0,1 ; ([MeasureBand45:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand46]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand46:%]/100) | 0,0,0,1 ; ([MeasureBand46:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand47]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand47:%]/100) | 0,0,0,1 ; ([MeasureBand47:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand48]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand48:%]/100) | 0,0,0,1 ; ([MeasureBand48:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand49]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand49:%]/100) | 0,0,0,1 ; ([MeasureBand49:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand50]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand50:%]/100) | 0,0,0,1 ; ([MeasureBand50:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand51]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand51:%]/100) | 0,0,0,1 ; ([MeasureBand51:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand52]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand52:%]/100) | 0,0,0,1 ; ([MeasureBand52:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand53]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand53:%]/100) | 0,0,0,1 ; ([MeasureBand53:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand54]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand54:%]/100) | 0,0,0,1 ; ([MeasureBand54:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand55]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand55:%]/100) | 0,0,0,1 ; ([MeasureBand55:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand56]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand56:%]/100) | 0,0,0,1 ; ([MeasureBand56:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand57]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand57:%]/100) | 0,0,0,1 ; ([MeasureBand57:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand58]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand58:%]/100) | 0,0,0,1 ; ([MeasureBand58:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand59]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand59:%]/100) | 0,0,0,1 ; ([MeasureBand59:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand60]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand60:%]/100) | 0,0,0,1 ; ([MeasureBand60:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand61]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand61:%]/100) | 0,0,0,1 ; ([MeasureBand61:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand62]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand62:%]/100) | 0,0,0,1 ; ([MeasureBand62:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand63]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand63:%]/100) | 0,0,0,1 ; ([MeasureBand63:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand64]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand64:%]/100) | 0,0,0,1 ; ([MeasureBand64:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand65]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand65:%]/100) | 0,0,0,1 ; ([MeasureBand65:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand66]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand66:%]/100) | 0,0,0,1 ; ([MeasureBand66:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand67]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand67:%]/100) | 0,0,0,1 ; ([MeasureBand67:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand68]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand68:%]/100) | 0,0,0,1 ; ([MeasureBand68:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand69]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand69:%]/100) | 0,0,0,1 ; ([MeasureBand69:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand70]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand70:%]/100) | 0,0,0,1 ; ([MeasureBand70:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand71]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand71:%]/100) | 0,0,0,1 ; ([MeasureBand71:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand72]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand72:%]/100) | 0,0,0,1 ; ([MeasureBand72:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand73]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand73:%]/100) | 0,0,0,1 ; ([MeasureBand73:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand74]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand74:%]/100) | 0,0,0,1 ; ([MeasureBand74:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand75]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand75:%]/100) | 0,0,0,1 ; ([MeasureBand75:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand76]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand76:%]/100) | 0,0,0,1 ; ([MeasureBand76:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand77]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand77:%]/100) | 0,0,0,1 ; ([MeasureBand77:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand78]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand78:%]/100) | 0,0,0,1 ; ([MeasureBand78:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand79]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand79:%]/100) | 0,0,0,1 ; ([MeasureBand79:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))

[MeterBand80]
Meter=String
X=(#Scale#*#Space#)r
Y=0r
FontSize=(#Scale#*#FontMultiplier#)
Text=#Sq1#
AntiAlias=1
DynamicVariables=1
InlineSetting=GradientColor | 180 | #VisualizerBandColor# ; 0.0 | #VisualizerBandColor# ; ([MeasureBand80:%]/100) | 0,0,0,1 ; ([MeasureBand80:%]/100) | 0,0,0,1 ; 1.0
InlinePattern=.*
Angle=(Rad(270))