[MeasureBand0Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=1
AverageSize=#AverageSize#

[MeasureBand1Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=2
AverageSize=#AverageSize#

[MeasureBand2Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=3
AverageSize=#AverageSize#

[MeasureBand3Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=4
AverageSize=#AverageSize#

[MeasureBand4Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=5
AverageSize=#AverageSize#

[MeasureBand5Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=6
AverageSize=#AverageSize#

[MeasureBand6Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=7
AverageSize=#AverageSize#

[MeasureBand7Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=8
AverageSize=#AverageSize#

[MeasureBand8Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=9
AverageSize=#AverageSize#

[MeasureBand9Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=10
AverageSize=#AverageSize#

[MeasureBand10Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=11
AverageSize=#AverageSize#

[MeasureBand11Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=12
AverageSize=#AverageSize#

[MeasureBand12Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=13
AverageSize=#AverageSize#

[MeasureBand13Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=14
AverageSize=#AverageSize#

[MeasureBand14Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=15
AverageSize=#AverageSize#

[MeasureBand15Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=16
AverageSize=#AverageSize#

[MeasureBand16Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=17
AverageSize=#AverageSize#

[MeasureBand17Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=18
AverageSize=#AverageSize#

[MeasureBand18Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=19
AverageSize=#AverageSize#

[MeasureBand19Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=20
AverageSize=#AverageSize#

[MeasureBand20Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=21
AverageSize=#AverageSize#

[MeasureBand21Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=22
AverageSize=#AverageSize#

[MeasureBand22Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=23
AverageSize=#AverageSize#

[MeasureBand23Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=24
AverageSize=#AverageSize#

[MeasureBand24Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=25
AverageSize=#AverageSize#

[MeasureBand25Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=26
AverageSize=#AverageSize#

[MeasureBand26Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=27
AverageSize=#AverageSize#

[MeasureBand27Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=28
AverageSize=#AverageSize#

[MeasureBand28Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=29
AverageSize=#AverageSize#

[MeasureBand29Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=30
AverageSize=#AverageSize#

[MeasureBand30Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=31
AverageSize=#AverageSize#

[MeasureBand31Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=32
AverageSize=#AverageSize#

[MeasureBand32Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=33
AverageSize=#AverageSize#

[MeasureBand33Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=34
AverageSize=#AverageSize#

[MeasureBand34Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=35
AverageSize=#AverageSize#

[MeasureBand35Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=36
AverageSize=#AverageSize#

[MeasureBand36Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=37
AverageSize=#AverageSize#

[MeasureBand37Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=38
AverageSize=#AverageSize#

[MeasureBand38Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=39
AverageSize=#AverageSize#

[MeasureBand39Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=40
AverageSize=#AverageSize#

[MeasureBand40Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=41
AverageSize=#AverageSize#

[MeasureBand41Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=42
AverageSize=#AverageSize#

[MeasureBand42Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=43
AverageSize=#AverageSize#

[MeasureBand43Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=44
AverageSize=#AverageSize#

[MeasureBand44Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=45
AverageSize=#AverageSize#

[MeasureBand45Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=46
AverageSize=#AverageSize#

[MeasureBand46Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=47
AverageSize=#AverageSize#

[MeasureBand47Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=48
AverageSize=#AverageSize#

[MeasureBand48Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=49
AverageSize=#AverageSize#

[MeasureBand49Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=50
AverageSize=#AverageSize#

[MeasureBand50Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=51
AverageSize=#AverageSize#

[MeasureBand51Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=52
AverageSize=#AverageSize#

[MeasureBand52Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=53
AverageSize=#AverageSize#

[MeasureBand53Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=54
AverageSize=#AverageSize#

[MeasureBand54Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=55
AverageSize=#AverageSize#

[MeasureBand55Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=56
AverageSize=#AverageSize#

[MeasureBand56Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=57
AverageSize=#AverageSize#

[MeasureBand57Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=58
AverageSize=#AverageSize#

[MeasureBand58Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=59
AverageSize=#AverageSize#

[MeasureBand59Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=60
AverageSize=#AverageSize#

[MeasureBand60Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=61
AverageSize=#AverageSize#

[MeasureBand61Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=62
AverageSize=#AverageSize#

[MeasureBand62Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=63
AverageSize=#AverageSize#

[MeasureBand63Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=64
AverageSize=#AverageSize#

[MeasureBand64Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=65
AverageSize=#AverageSize#

[MeasureBand65Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=66
AverageSize=#AverageSize#

[MeasureBand66Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=67
AverageSize=#AverageSize#

[MeasureBand67Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=68
AverageSize=#AverageSize#

[MeasureBand68Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=69
AverageSize=#AverageSize#

[MeasureBand69Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=70
AverageSize=#AverageSize#

[MeasureBand70Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=71
AverageSize=#AverageSize#

[MeasureBand71Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=72
AverageSize=#AverageSize#

[MeasureBand72Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=73
AverageSize=#AverageSize#

[MeasureBand73Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=74
AverageSize=#AverageSize#

[MeasureBand74Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=75
AverageSize=#AverageSize#

[MeasureBand75Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=76
AverageSize=#AverageSize#

[MeasureBand76Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=77
AverageSize=#AverageSize#

[MeasureBand77Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=78
AverageSize=#AverageSize#

[MeasureBand78Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=79
AverageSize=#AverageSize#

[MeasureBand79Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=80
AverageSize=#AverageSize#

[MeasureBand80Raw]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Channel=#MeasureChannel#
Type=Band
BandIdx=81
AverageSize=#AverageSize#
