[MeasureDiscordHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=Discord.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureTelegramHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=Telegram.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureSlackHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=slack.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureSteamHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=steamwebhelper.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureBattleNetHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=Battle.net.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureUbisoftConnectHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=upc.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureGOGConnectHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=GalaxyClient.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureWebstormHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=webstorm64.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureVSCodeHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=Code.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureAndroidStudioHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=studio64.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureObsStudioHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=obs64.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureSoundBoardHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=DCSB.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureGimpHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=gimp-2.10.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureAudacityHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=Audacity.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureBlenderHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=blender.exe
Substitute="1":"0","-1":"1","-0":"1"

[MeasureHandBreakHideRunning]
Measure=Plugin
Plugin=Process
ProcessName=HandBrake.exe
Substitute="1":"0","-1":"1","-0":"1"