[RunMeasureDiscord]
Measure=Plugin
Plugin=RunCommand
Program="C:\Users\tedeusz\AppData\Local\Discord\Update.exe"
Parameter="--processStart Discord.exe"
State=Hide

[RunMeasureTelegram]
Measure=Plugin
Plugin=RunCommand
Program="C:\Users\tedeusz\AppData\Roaming\Telegram Desktop\Telegram.exe"
State=Hide

[RunMeasureSlack]
Measure=Plugin
Plugin=RunCommand
Program="C:\Users\tedeusz\AppData\Local\slack\slack.exe"
State=Hide

[RunMeasureSteam]
Measure=Plugin
Plugin=RunCommand
Program="C:\Program Files (x86)\Steam\steam.exe"
State=Hide

[RunMeasureBattleNet]
Measure=Plugin
Plugin=RunCommand
Program="C:\Program Files (x86)\Battle.net\Battle.net.exe"
State=Hide

[RunMeasureUbisoftConnect]
Measure=Plugin
Plugin=RunCommand
Program="C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\UbisoftConnect.exe"
State=Hide

[RunMeasureGOG]
Measure=Plugin
Plugin=RunCommand
Program="C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe"
State=Hide